data: 
  csv_path: 
  H: 720
  W: 1280
  initial_len:  1667
  window_len: 1667

dbscan: 
  eps: 8
  min_samples: 5
  time_scale: 0.0005 

save_video_p:
  save_video: False
  fps: 10
  out_path: "debug_tracking.mp4"

kalman:
  sort:
    max_distance: 30
    t_found: 4
    t_lost: 12

  initial_uncertainty_P:
    x: 25
    y: 25
    area: 500
    vx: 500
    vy: 500
    varea: 2000

  process_noise_Q:
    x: 5
    y: 5
    area: 50
    vx: 120
    vy: 120
    varea: 200

  measurement_noise_R:
    x: 30
    y: 30
    area: 300

frequency:
    box_shift: 25
    min_freq: 200
    max_freq: 300
    freq_res: 1