data: 
  csv_path: "C:\\Users\\user\\Documents\\Uni Materials 3\\Blob Frequency Extractor\\background_only.csv"
  #csv_path: "C:\\Users\\user\\Documents\\Uni Materials 3\\Blob Frequency Extractor\\insect_combined\\full_trajectories\\all_bees\\13_bee_pts1692_start12317637.csv"
  H: 720
  W: 1280
  initial_len:  1667
  window_len: 1667

dbscan: 
  eps: 5
  min_samples: 3
  time_scale: 0.001

save_video_p:
  save_video: False
  save_tracks_events: True
  fps: 10
  out_path: "debug_tracking.mp4"

kalman:
  sort:
    max_distance: 30
    t_found: 3
    t_lost: 4

  initial_uncertainty_P:
    x: 10
    y: 10
    area: 500
    vx: 500
    vy: 500
    varea: 2000

  process_noise_Q:
    x: 2.5
    y: 2.5
    area: 50
    vx: 120
    vy: 120
    varea: 200

  measurement_noise_R:
    x: 2
    y: 2
    area: 100

frequency:
    box_shift: 25
    min_freq: 150
    max_freq: 300
    freq_res: 0.1
    mag_tresh: 0
 
    